"""Offline provider for tests and demos.

Produces deterministic, well-formed replies for every agent role so the whole pipeline
(including guardrails, metrics, and reports) runs with no API key. Output is clearly marked
as mock everywhere it appears; it is plumbing, not simulated research.
"""

from __future__ import annotations

import hashlib
import json
import random
import re
from typing import Any


def _rng(*parts: Any) -> random.Random:
    key = "|".join(str(p) for p in parts).encode()
    return random.Random(int.from_bytes(hashlib.sha256(key).digest()[:8], "big"))


OPENERS = ["Honestly, for me", "The way I see it,", "Speaking for my household,", "I'll be blunt:", "Good question."]
BODIES = [
    "it comes down to whether it fits my routine.",
    "price is the first thing I look at.",
    "I'd need to try it before I believed any of that.",
    "the claims sound nice but I've heard them before.",
    "if it tastes right, I'm not that fussy about the rest.",
    "I care more about what's in it than what it costs.",
    "I don't trust a label just because it says sustainable.",
    "I'd pay a bit more if it actually lasted longer in the fridge.",
]
CLOSERS = ["", " That's the deal-breaker for me.", " I'd still compare it with what I buy now.", " Maybe if it were on sale."]

THEME_RULES = [
    ("Price decides whether people try it", r"price|\bpay\b|cost|on sale", "most"),
    ("Claims are met with skepticism", "claim|trust|label|believe", "several"),
    ("Taste and routine drive repeat purchase", "taste|routine|try|fridge", "several"),
]


class MockProvider:
    name = "mock"

    def complete(self, *, model, system, messages, temperature, max_tokens, meta):
        role = meta.get("role")
        handler = getattr(self, f"_{role}", None)
        if handler is None:
            raise ValueError(f"mock provider has no handler for role '{role}'")
        return handler(meta)

    # -- roles ---------------------------------------------------------------

    def _backstory(self, meta: dict) -> str:
        p = meta["persona"]
        r = _rng("backstory", p["id"])
        traits = "; ".join(p["described"][:3])
        quirk = r.choice(["reads every label twice", "keeps a spreadsheet of grocery prices", "shops at two stores to get the best deals", "never switches brands without a coupon"])
        return (
            f"[MOCK] {p['name']} is a synthetic test participant ({traits}). "
            f"They shop for this category every week and usually stick with what they know. "
            f"Friends know them as someone who {quirk}."
        )

    def _rating(self, meta: dict) -> str:
        item, p = meta["item"], meta["persona"]
        low, high = item["low"], item["high"]
        r = _rng("rating", p["id"], item["id"], meta.get("phase"), meta.get("attempt"))
        score = (low + high) / 2
        for exp in item.get("expect", []):
            a = p["numeric"].get(exp["attribute"])
            if not a or "low" not in a:
                continue
            centered = (a["value"] - (a["low"] + a["high"]) / 2) / ((a["high"] - a["low"]) / 2)
            sign = 1 if exp["direction"] == "positive" else -1
            score += sign * centered * (high - low) * 0.35
        score += r.gauss(0, 0.8)
        if meta.get("phase") == "post" and meta.get("own_pre") is not None and meta.get("group_mean_pre") is not None:
            # simulate social influence: move part of the way toward the group's opening average
            score = meta["own_pre"] + 0.45 * (meta["group_mean_pre"] - meta["own_pre"]) + r.gauss(0, 0.3)
        rating = max(low, min(high, int(round(score))))
        return json.dumps({"rating": rating, "reason": "[MOCK] Reason generated by the offline test provider."})

    def _participant(self, meta: dict) -> str:
        p = meta["persona"]
        r = _rng("participant", p["id"], meta.get("turn_index"))
        prefix = ""
        others = meta.get("others") or []
        if others and r.random() < 0.4:
            other = r.choice(others)
            prefix = r.choice([f"I'm with {other} on that. ", f"I see it differently from {other}. "])
        opener, body = r.choice(OPENERS), r.choice(BODIES)
        if opener.endswith((".", ":")):
            body = body[0].upper() + body[1:]
        return f"{prefix}{opener} {body}{r.choice(CLOSERS)}"

    def _moderator(self, meta: dict) -> str:
        topic, used, budget = meta["topic"], meta["used"], meta["budget"]
        unheard, recent = meta["unheard"], meta["recent_speakers"]
        if used == 0:
            action = {"action": "ask_group", "text": topic["question"]}
        elif unheard:
            action = {"action": "ask_participant", "participant": unheard[0], "text": f"{unheard[0]}, what's your take?"}
        elif used < budget - 2 and topic.get("probes") and recent:
            probe = topic["probes"][used % len(topic["probes"])]
            action = {"action": "probe", "participant": recent[-1], "text": probe}
        elif used < budget - 1:
            action = {"action": "ask_group", "text": "Does anyone see it differently?"}
        else:
            action = {"action": "next_topic", "text": "Thanks, that gives us a clear picture on this one."}
        return json.dumps(action)

    def _analyst(self, meta: dict) -> str:
        lines: list[list[str]] = meta.get("lines", [])
        themes = []
        for title, pattern, prevalence in THEME_RULES:
            quotes = []
            for speaker, text in lines:
                if len(quotes) >= 2 or speaker in {q["speaker"] for q in quotes}:
                    continue
                sentences = re.split(r"(?<=[.!?])\s+", text.strip())
                match = next((x for x in sentences if re.search(pattern, x, re.I)), None)
                if match:
                    quotes.append({"speaker": speaker, "quote": match})
            themes.append({
                "title": title,
                "description": "[MOCK] Theme assembled by keyword matching in the offline test provider.",
                "prevalence": prevalence,
                "quotes": quotes,
            })
        return json.dumps({
            "headline": "[MOCK] Offline test run: findings below exercise the pipeline, not real research.",
            "summary": "[MOCK] This report was produced by the offline test provider. Run with a real provider to get an actual analysis.",
            "themes": themes,
            "disagreements": ["[MOCK] Participants split on whether price or taste matters more."],
            "open_questions": ["[MOCK] How would results differ with real respondents?"],
        })
